#! /usr/bin/env python
# -*- coding: utf-8 -*-

# We define run to be a kind of command utility
# It read settings.py and walk through the specified site
#
# Now let's begin

from crawler import CrawlerEngine
from settings import SITE

if __name__ == '__main__':
    engine = CrawlerEngine([SITE,])
    engine.start()
